# Suggested labels for issues and PRs. Can be used with actions that create labels from a file.
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: question
  color: cc317c
  description: Further information is requested
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
